#!/bin/bash

set -e

path="$HOME/.zshell"

if [ -e $path/.git ]; then
  cd $path && git pull
else
  git clone https://github.com/filippoliverani/zshell.git $path
fi

brew install starship zsh fzf zplug zsh-autosuggestions
npm install --global pure-prompt

ln -sf $path/zshrc ~/.zshrc
ln -sf $path/zsh_aliases ~/.zsh_aliases
mkdir -p "$HOME/.zsh_cache"

sudo sh -c "echo $(which zsh) >> /etc/shells"
chsh -s $(which zsh)

zsh -c "source ~/.zshrc && zplug install"
