#!/bin/sh

path="$HOME/.zolarizedsh"

if [ -e $path/.git ]; then
    cd $path && git pull
else
    git clone https://github.com/filippo-liverani/zolarizedsh.git $path
fi

curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh

ln -sfT $path/zshrc ~/.zshrc
ln -sfT $path/zsh_aliases ~/.zsh_aliases

chsh -s $(which zsh)
