#!/bin/sh

path="$HOME/.zolarizedsh"

git clone git@github.com:filippo-liverani/zolarizedsh.git $path

curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh

ln -sfT $path/zshrc ~/.zshrc
